### ISSUE TITLE
Worker-ResourceReload-1

### ISSUE THREAD

**Issue by Sultia** [Technici4n/Powah#116]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.20.1
- Forge: 47.2.6
- Powah: 5.0.4

#### Issue description:

[12:11:40] [Worker-ResourceReload-1/ERROR]: Failed to load model mahoutsukai:models/item/proximity_projection_keys2.json
com.google.gson.JsonParseException: Composite model requires a "children" element with at least one element.
	at net.minecraftforge.client.model.CompositeModel$Loader.read(CompositeModel.java:398) ~[forge-1.20.1-47.2.6-universal.jar%23763!/:?]
	at net.minecraftforge.client.model.CompositeModel$Loader.read(CompositeModel.java:381) ~[forge-1.20.1-47.2.6-universal.jar%23763!/:?]
	at net.minecraftforge.client.model.ExtendedBlockModelDeserializer.deserializeGeometry(ExtendedBlockModelDeserializer.java:99) ~[forge-1.20.1-47.2.6-universal.jar%23763!/:?]
	at net.minecraftforge.client.model.ExtendedBlockModelDeserializer.deserialize(ExtendedBlockModelDeserializer.java:55) ~[forge-1.20.1-47.2.6-universal.jar%23763!/:?]
	at net.minecraftforge.client.model.ExtendedBlockModelDeserializer.deserialize(ExtendedBlockModelDeserializer.java:38) ~[forge-1.20.1-47.2.6-universal.jar%23763!/:?]
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:76) ~[gson-2.10.jar%23107!/:?]
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:524) ~[client-1.20.1-20230612.114412-srg.jar%23758!/:?]
	at net.minecraft.util.GsonHelper.m_263475_(GsonHelper.java:531) ~[client-1.20.1-20230612.114412-srg.jar%23758!/:?]
	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:581) ~[client-1.20.1-20230612.114412-srg.jar%23758!/:?]
	at net.minecraft.client.renderer.block.model.BlockModel.m_111461_(BlockModel.java:74) ~[client-1.20.1-20230612.114412-srg.jar%23758!/:?]
	at net.minecraft.client.resources.model.ModelManager.m_246478_(ModelManager.java:110) ~[client-1.20.1-20230612.114412-srg.jar%23758!/:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]

#### Steps to reproduce:

Load the game up and look at logs.

#### Is this a crash?, please include it here: (Recommended to use [Gist](https://gist.github.com/))

No

**Comment by Technici4n** [comment]
Sounds like a mahou tsukai problem?
