### ISSUE TITLE
Can't smelt raw uraninite

### ISSUE THREAD

**Issue by So1embum** [Technici4n/Powah#34]
#### Version: (make sure you are on the latest version before reporting):

- Minecraft: 1.19.2
- Fabric: 0.14.9
- Powah: 4.0.1-aplha

#### Issue description:
Can't smelt raw uraninite in furnaces

#### Steps to reproduce:
Place raw uraninite in furnace

#### Is this a crash?, please includ it here: (Recommended to use [Gist](https://gist.github.com/))
Doesn't crash, but it does throw an error when starting the client.

[20:33:59] [Render thread/ERROR]: Parsing error loading recipe powah:smelting/uraninite_from_raw
com.google.gson.JsonSyntaxException: Expected result to be a string, was an object ({"it...e"})
	at Not Enough Crashes deobfuscated stack trace.(1.19.2+build.4) ~[?:?]
	at net.minecraft.util.JsonHelper.asString(JsonHelper:111) ~[?:?]
	at net.minecraft.util.JsonHelper.getString(JsonHelper:117) ~[?:?]
	at net.minecraft.recipe.CookingRecipeSerializer.read(CookingRecipeSerializer:31) ~[?:?]
	at net.minecraft.recipe.CookingRecipeSerializer.read(CookingRecipeSerializer:11) ~[?:?]
	at net.minecraft.recipe.RecipeManager.deserialize(RecipeManager:135) ~[?:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager:56) ~[?:?]
	at net.minecraft.recipe.RecipeManager.apply(RecipeManager:35) ~[?:?]
	at net.minecraft.resource.SinglePreparationResourceReloader.method_18790(SinglePreparationResourceReloader:13) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.resource.SimpleResourceReload.method_18365(SimpleResourceReload:69) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.executeTask(ThreadExecutor:157) ~[?:?]
	at net.minecraft.util.thread.ReentrantThreadExecutor.executeTask(ReentrantThreadExecutor:23) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTask(ThreadExecutor:131) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.runTasks(ThreadExecutor:140) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServerLoader.createSaveLoader(IntegratedServerLoader:136) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServerLoader.createSaveLoader(IntegratedServerLoader:117) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServerLoader.start(IntegratedServerLoader:150) ~[?:?]
	at net.minecraft.server.integrated.IntegratedServerLoader.start(IntegratedServerLoader:57) ~[?:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$WorldEntry.start(WorldListWidget:528) ~[?:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$WorldEntry.play(WorldListWidget:436) ~[?:?]
	at net.minecraft.client.gui.screen.world.WorldListWidget$WorldEntry.mouseClicked(WorldListWidget:372) ~[?:?]
	at net.minecraft.client.gui.widget.EntryListWidget.mouseClicked(EntryListWidget:372) ~[?:?]
	at net.minecraft.client.gui.ParentElement.mouseClicked(ParentElement:27) ~[?:?]
	at net.minecraft.client.Mouse.method_1611(Mouse:94) ~[?:?]
	at net.minecraft.client.gui.screen.Screen.wrapScreenError(Screen:489) ~[?:?]
	at net.minecraft.client.Mouse.onMouseButton(Mouse:94) ~[?:?]
	at net.minecraft.client.Mouse.method_22686(Mouse:165) ~[?:?]
	at net.minecraft.util.thread.ThreadExecutor.execute(ThreadExecutor:103) ~[?:?]
	at net.minecraft.client.Mouse.method_22684(Mouse:165) ~[?:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.3.1.jar:?]
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133) ~[FpsReducer2-fabric-1.19.2-2.1.jar:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar:?]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar:?]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3474) ~[lwjgl-glfw-3.3.1.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.handler$cif000$handleWaitEventsTimeout(RenderSystem:2483) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.limitDisplayFPS(RenderSystem) ~[client-intermediary.jar:?]
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1208) ~[?:?]
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768) ~[?:?]
	at net.minecraft.client.main.Main.main(Main:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.9.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.polymc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175) [NewLaunch.jar:?]
	at org.polymc.impl.OneSixLauncher.launch(OneSixLauncher.java:185) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.listen(EntryPoint.java:144) [NewLaunch.jar:?]
	at org.polymc.EntryPoint.main(EntryPoint.java:74) [NewLaunch.jar:?]

**Comment by andrewsf** [comment]
I believe the [correct format for cooking recipes](https://minecraft.fandom.com/wiki/Recipe#JSON_format) is `"result": "powah:uraninite"`, not `"result": { "item": "powah:uraninite" }`

[Random example from Mekanism](https://raw.githubusercontent.com/mekanism/Mekanism/82b232ebf99dc0a4dca752c99301a4b2471d57c6/src/datagen/generated/mekanismtools/data/mekanismtools/recipes/iron_nugget_from_smelting.json).

I'm not sure why there are accounts of this format working and even being able to smelt multiple items -- when deserializing the JSON the core minecraft code only reads "result" as a string.

**Comment by Technici4n** [comment]
Fixed, thanks @andrewsf for the insight.
